FROM python:3.9 as build
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1
WORKDIR /code

# install our dependencies
# we use --system flag because we don't need an extra virtualenv
COPY Pipfile Pipfile.lock /code/
RUN pip install pipenv && pipenv install --system

# copy our project code
COPY . /code/
