# Generated by Django 4.1.5 on 2023-01-03 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='source',
            field=models.CharField(default='remoteok', max_length=100),
            preserve_default=False,
        ),
    ]
